### ISSUE TITLE
HTML5 tags

### ISSUE THREAD

**Issue by be5invis** [brechtm/rinohtype#1]
Rinohtype is a wonderful document generator, but I am wondering that whether you can use HTML5 tags and a CSS-like styling system for input, such as `<table>` instead of `<tabular>`. It may help publishing your document to both the web and the print.

**Comment by brechtm** [comment]
rinohtype no longer supports the custom XML format that I started out with. The idea is now to support existing document formats by means of a set of frontends. ReStructuredText/Sphinx has the best support at the moment, but there are basic frontends for CommonMark, DocBook  and ePub too. A non-free [DITA XML](https://en.wikipedia.org/wiki/Darwin_Information_Typing_Architecture) frontend is under development. In the same way, it is possible to write a HTML5 frontend. It is probably a good idea to limit this to a subset of HTML5 that is better suited as structured text format such as [HTMLBook](http://oreillymedia.github.io/HTMLBook/). Contributions welcome!

rinohtype now also features a capable stylesheet system, which has been inspired by CSS. Please refer to the [documentation](http://www.mos6581.org/rinohtype/) for details.
