### ISSUE TITLE
Python 3.5 is not supported

### ISSUE THREAD

**Issue by frol** [brechtm/rinohtype#10]
When I run RinohType on Python 3.5 (I haven't tried 3.4 or earlier versions), I get the traceback:

```python
  File "/tmp/env/lib/python3.5/site-packages/rinoh/backend/pdf/cos.py", line 75, in <module>
    class Null(Object, NoneType):
TypeError: type 'NoneType' is not an acceptable base type
```

**Comment by frol** [comment]
The related issue in Python bugtracker: https://bugs.python.org/issue24806

**Comment by brechtm** [comment]
This is fixed in master (47625d5) but not yet in a release.

**Comment by frol** [comment]
Could you please make a release?

**Comment by brechtm** [comment]
I'm currently making some major changes to the way document templates work. Once this architecture has stabilized, I plan to create a new release. This can take a couple of weeks though...

**Comment by frol** [comment]
@brechtm Sounds great! I really like RinohType!
