### ISSUE TITLE
How can I hide the date on the title page of a document?

### ISSUE THREAD

**Issue by nathalipaz** [brechtm/rinohtype#101]
I am new with rinohtype and rst files.
I just want to know how I can remove default Date.
Thank you very much

**Comment by brechtm** [comment]
I assume you're using [`rinoh`](http://www.mos6581.org/rinohtype/quickstart.html#command-line-renderer) to render a reStructuredText file. I also assume you are talking about the date displayed on the title page? You can go about suppressing it in two ways. Both result in the same output, so it doesn't matter which option you choose.

I realize this may not be obvious to anyone but myself at this point, so I have taken the time to explain this elaborately with links to the relevant parts in the [documentation](http://www.mos6581.org/rinohtype/). Let me know if anything is not clear!

### Option 1: Template Configuration

The title page template has a [show_date](http://www.mos6581.org/rinohtype/api/template.html#rinoh.template.TitlePageTemplate.show_date) configuration option. You can set it to `false` by [creating a template configuration](http://www.mos6581.org/rinohtype/basicstyling.html#configuring-a-template). Here is what it would look like:

```ini
[TEMPLATE_CONFIGURATION]
name = my article template configuration
template = article

[title_page]
show_date = false
```

Save this file as `demo.rtt` and pass it along to `rinoh`:

    rinoh -f restructuredtext --template demo.rtt demo.txt

### Option 2: Style Sheet

This is a more general approach. A Style sheet allows you to hide any element(s), provided you can ["select"](http://www.mos6581.org/rinohtype/elementstyling.html#selectors) them. If you look at the [`.stylelog` file](http://www.mos6581.org/rinohtype/elementstyling.html#style-logs) output after rendering your document, you can find the element corresponding to the date on the title page (page 1):

```python
Paragraph('January 03, 2012', style='title page date')
```

We can use this to create a [custom selector](http://www.mos6581.org/rinohtype/elementstyling.html#custom-selectors) for use in a [style sheet](http://www.mos6581.org/rinohtype/basicstyling.html#basics-stylesheets):

```ini
[STYLESHEET]
name = my style tweaks
base = sphinx_article

[title page date : Paragraph('title page date')]
hide = true
```

Save this file as `demo.rts` and pass it along to `rinoh`:

    rinoh -f restructuredtext --stylesheet demo.rts demo.txt

**Comment by nathalipaz** [comment]
thank you, option 1 is perfect for me
