### ISSUE TITLE
Return code 0 despite failure to include images

### ISSUE THREAD

**Issue by hartwork** [brechtm/rinohtype#104]
Hi there!

I noticed that rinohtype 0.3.1 does not propagate failures to include images to the return code:
```
# rinoh README.rst ; echo $?
[..]
[README.rst:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/tmp.0lBWTSCDS5/http:/img.shields.io/pypi/v/rinohtype.svg'
[README.rst:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/tmp.0lBWTSCDS5/[..].svg'
[README.rst:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/tmp.0lBWTSCDS5/[..].png'
[README.rst:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/tmp.0lBWTSCDS5/[..]'
[README.rst:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/tmp.0lBWTSCDS5/[..].svg'
[README.rst:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/tmp.0lBWTSCDS5/[..].svg'
[..]
Writing output: README.pdf
0
```
Please make it return non-zero so automation built around it, say a Makefile, has a better chance to notice errors quickly.

Thanks and best, Sebastian

PS: This is with rinohtype's own `README.rst`. So there may be an issue with remote image support as well.

**Comment by brechtm** [comment]
Thanks for the suggestion. I think it's a good idea.

> PS: This is with rinohtype's own README.rst. So there may be an issue with remote image support as well.

Remote images are currently not supported. I looked into adding support for it some time ago, but it was more complex than I anticipated. It's not a priority at the moment...

**Comment by hartwork** [comment]
Thanks!
