### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by sid-kap** [brechtm/rinohtype#115]
It seems like there haven't been any commits in over a year. Is this project still being developed?

**Comment by brechtm** [comment]
It seems that way indeed. The latest changes were only pushed to the stable branch, however. While the project is not abandoned, I don't have much time to work on it at the moment. I'm planning on getting rid of the stable branch (after merging it to master) and create a new release.

That said, the current release should be able to render most reStructuredText and Sphinx documents. Please create a new issue ticket if you run into any problems. Thanks.

**Comment by sid-kap** [comment]
Thanks!
