### ISSUE TITLE
errors in rinoh.frontend.sphinx

### ISSUE THREAD

**Issue by TkMyrm** [brechtm/rinohtype#131]
Hei Brecht,

ran into two small problems with the rinoh for sphinx:

frontend\sphinx\__init__.py", line 225:
suffix, = 'pdf'
ValueError: too many values to unpack (expected 1)

frontend\sphinx\__init__.py", line 227:
source_path = os.path.join(self.srcdir, docname + suffix)
TypeError: Can't convert 'list' object to str implicitly

I removed the ',' from suffix variable and removed 'suffix' completely from source_path and got a successful render (now I have a lot of formatting todo...) but thought you might like to know.
my version looks like this:
        suffix = config.source_suffix
        source_path = os.path.join(self.srcdir, docname)

the suffix is successfully added elsewhere :)
thanks for making this!

**Comment by devopsec** [comment]
same issue for me and the same changes fixed build as well.

My environment:

```
> python3 -V
Python 3.5.2
> sphinx-build --version
sphinx-build 1.8.1
> rinoh --version
rinoh 0.3.1 (2016-12-19)
```

**Comment by brechtm** [comment]
Yes, this has been fixed. Thanks for reporting!
