### ISSUE TITLE
Support with Sphinx version >= 2.0

### ISSUE THREAD

**Issue by cmg2puva** [brechtm/rinohtype#140]
When updating the installed version of Sphinx to a version greater than 2.0 (latest is 2.0.1), the building of the PDF errors out:

**Exception occurred:
rinoh\frontend\sphinx\__init__.py, line 211, in write self.info("processing " + targetname + "...", nonl=1)
AttributeError: 'RinohBuilder' object has no attribute 'info'**

Downgrading to a previous version of Sphinx does not cause this same issue.

**Comment by khink** [comment]
+1

**Comment by av8r** [comment]
Hi

I fixed it with the following patch:
[rinohtype-sphinx.diff.txt](https://github.com/brechtm/rinohtype/files/3931725/rinohtype-sphinx.diff.txt)

**Comment by khink** [comment]
That's great @av8r ! If you made a PR, do you think someone would merge it and make a release?

**Comment by brechtm** [comment]
Thanks for reporting. The fix will be included in the next release.
