### ISSUE TITLE
AttributeError: 'RinohBuilder' object has no attribute 'info'

### ISSUE THREAD

**Issue by butayama** [brechtm/rinohtype#143]
The full traceback has been saved in /tmp/sphinx-err-xatjw29d.log
[sphinx-err-xatjw29d.log](https://github.com/brechtm/rinohtype/files/4143853/sphinx-err-xatjw29d.log)

**Comment by brechtm** [comment]
Thanks for reporting this. This issue has been fixed in the master branch (4333d4b54fb5f543b673e0f927551cbe03a9f66c) and will be included in the next release which I will soon make.
