### ISSUE TITLE
Add support for plantuml extension diagrams

### ISSUE THREAD

**Issue by vtexier** [brechtm/rinohtype#155]
Thanks a lot for the example code you gave me in #118.

I will be glad to contribute adding support to plantuml in rinoh if possible.

I have implemented the code example in `rinoh/frontend/rst/nodes.py`:

```python
class PlantUML(DocutilsBodyNode):
    def build_flowable(self):

        # TODO: generate image
        from sphinxcontrib.plantuml import rinoh_visit_plantuml
        image_node = rinoh_visit_plantuml(????, self)

        # TODO: get image path from rendered plantuml node
        image_path = image_node.????

        width_string = self.get('width')
        align = self.get('align')
        return Image(image_path, scale=self.get('scale', 100) / 100,
                     width=convert_quantity(width_string), align=align)
```
and a `rinoh_visit_plantuml(self, node)` in `plantuml.py`.

Reading the code in graphviz extension, it seems I need a `SphinxTranslator` instance in self, to access `self.builder.srcdir` in `plantuml.py`.

But I do not find any Translator instance in rinoh...

Thanks for any help.

**Comment by brechtm** [comment]
I believe all of this code belongs in the [PlantUML Sphinx extension](/sphinx-contrib/plantuml). You'll need to include the *try/except ImportError* construct there, of course.

It's not possible to have a `rinoh_visit_plantuml` method, for reasons explained in #118. But indeed, I now see that the extension passes along the translator to determine the `srcdir` path. As far as I can see, it only accesses the builder attribute of the translator. rinohtype does have a builder, thankfully. How to access that, is another question...

This will requires changes in rinohtype, in or before [this line](https://github.com/brechtm/rinohtype/blob/0a5bb07b439e62ac922a5dd3c657dcb3504d2fac/src/rinoh/frontend/sphinx/__init__.py#L230). Either pass along the builder (or just srcdir) to `from_doctree` (and `map_node`), but that will require changes in a lot of places. Or, a more hacky solution, store a reference to the builder in the root node (`doctree`) and retrieve it when needed (in `PlantUML.build_flowable`).

**Comment by brechtm** [comment]
> This will require changes in rinohtype, in or before [this line](https://github.com/brechtm/rinohtype/blob/0a5bb07b439e62ac922a5dd3c657dcb3504d2fac/src/rinoh/frontend/sphinx/__init__.py#L230). Either pass along the builder (or just srcdir) to `from_doctree` (and `map_node`), but that will require changes in a lot of places.

Actually, the amount in changes required is limited. Once I figure out proper variable naming, I'll commit :-)

**Comment by brechtm** [comment]
In the master branch, you can now access the builder instance from within `build_flowable()` as `self.context['sphinx_builder']` and access its `srcdir` attribute.

**Comment by vtexier** [comment]
Great! Thanks!

I managed to get the image path of the rendered diagram. 

Plantuml rendering integrates in rinoh with a little hack for the SphinxTranslator. No big deal.

```python
# in site-packages/rinoh/frontend/rst/nodes.py
class PlantUML(DocutilsBodyNode):
    def build_flowable(self):

        try:
            # import renderer from plantuml extension
            from sphinxcontrib.plantuml import rinoh_render_plantuml
        except ImportError as e:
            return self

        # plantuml need only the sphinx builder from a SphinxTranslator
        class PseudoSphinxTranslator:
            builder = self.context['sphinx_builder']

        # get image path of the rendered diagram
        image_path = rinoh_render_plantuml(PseudoSphinxTranslator(), self)

        width_string = self.get('width')
        align = self.get('align')
        return Image(image_path, scale=self.get('scale', 100) / 100,
                     width=convert_quantity(width_string), align=align)
```

But then I got an error, like rinoh is not happy with the returned Image object...

```
  File "/home/vit/Documents/dev/big_data/madam/documentation/.venv/lib/python3.8/site-packages/rinoh/frontend/rst/__init__.py", line 38, in node_children
    return node.children
AttributeError: 'str' object has no attribute 'children'
```

**Comment by brechtm** [comment]
> But then I got an error, like rinoh is not happy with the returned Image object...

That is because the _Image_ class in `rinoh/frontend/rst/nodes.py` is not the one you need. You need _Image_ from `rinoh.image` (also available from `rinoh`).

**Comment by vtexier** [comment]
Ok. I managed to make it work.

Here is the result of my tests...

#### Using plantuml rendering in "eps" format
Rinoh convert it to png but the quality is too poor.
_Pillow dependency required._

#### Using plantuml rendering in "png" format
Rinoh crash in the purepng.py script (don't know why the need to open it in pure python...).
```
  File "/home/vit/Documents/dev/big_data/madam/documentation/.venv/lib/python3.8/site-packages/rinoh/backend/pdf/xobject/purepng.py", line 2570, in _process_iTXt
    assert (data[i + 1:i + 2] == zerobyte)
AssertionError
```

#### Using plantuml rendering in "svg" format
Rinoh display error message on images. Error messages in pdf too. 

`Error opening image file: cannot identify image file`

#### Conclusion
To make it really useful in production, plantuml diagrams should be rendered only in "eps" format and include in the pdf in a vector format, without converting to a bitmap format. If it's possible in rinoh.

_Another anoying problem out of the scope of this issue, the pdf document got one blank page between each chapter and three blank pages at the end._

**Comment by brechtm** [comment]
**EPS** cannot be embedded in PDF without conversion. Pillow is ignoring the vector content and extracting the bitmap thumbnail embedded in the EPS. That's why the quality is poor.

**PNG** should work. Please try with purepng from PyPI and create a bug report at [Scondo/purepng](https://github.com/scondo/purepng) if that fails? Or the generated PNG may be corrupt.

Like EPS, **SVG** images cannot be embedded in PDF.

Have you tried **PDF**?

**Comment by vtexier** [comment]
Thanks for the blank page hints.

For plantuml images. I do not have much time to spend on it, but I have setup a workflow that seems the best to me, keeping the quality and may be the vector format (I hope...).

> Have you tried PDF?

Yes! it is the idea...

So, this workflow requires a sphinx extension:
https://pypi.org/project/sphinxcontrib-svg2pdfconverter/

This extension requires Inskape or better, rsvglib:

```
# needed by sphinxcontrib-svg2pdfconverter
sudo apt-get install librsvg2-common librsvg2-bin
```
The purpose of this extension is to automatically convert SVG images to a format suitable for the builder.

So let's say we have SVG images for our HTML sphinx documentation or plantuml SVG rendered images.
sphinxcontrib-svg2pdfconverter will convert them to pdf for the rinoh builder.

I don't know how to handle it properly in rinoh, and my only try to convert in the plantuml node failed.

```
  File "/home/vit/Documents/dev/big_data/madam/documentation/.venv/lib/python3.8/site-packages/sphinx/transforms/post_transforms/images.py", line 194, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'document'
```

Here is the failing code, but it is dirty and need to be done automatically by sphinxcontrib-svg2pdfconverter in the rinoh workflow after plantuml directive has been rendered in SVG.

```python
class PlantUML(DocutilsBodyNode):
    def build_flowable(self):

        try:
            # generate SVG image with plantuml extension
            from sphinxcontrib.plantuml import rinoh_render_plantuml
        except ImportError as e:
            return self

        # plantuml need only the sphinx builder from a SphinxTranslator
        class PseudoSphinxTranslator:
            builder = self.context['sphinx_builder']

        # get image path from rendered plantuml node
        image_path = rinoh_render_plantuml(PseudoSphinxTranslator(), self)

        # get sphinxcontrib.rsvgconverter
        from sphinxcontrib.rsvgconverter import RSVGConverter
        svg2pdf_converter = RSVGConverter()

        # get path parts to set extension
        from pathlib import Path
        destination_path = Path(image_path)
        destination_path.suffix = 'pdf'

        # convert svg to pdf with rsvglib
        svg2pdf_converter.convert(image_path, str(destination_path))

        # return pdf
        width_string = self.get('width')
        align = self.get('align')
        return rt.Image(str(destination_path), scale=self.get('scale', 100) / 100,
                     width=convert_quantity(width_string), align=align)
```

If you manage to integrate smoothly sphinxcontrib-svg2pdfconverter in rinoh, it will support SVG seamlessly, hopefully for plantuml too.

**Comment by brechtm** [comment]
[sphinxcontrib/plantuml.py](/sphinx-contrib/plantuml/blob/master/sphinxcontrib/plantuml.py) already includes code to convert EPS to PDF (`_convert_eps_to_pdf`), so there is no need for sphinxcontrib-svg2pdfconverter.

As a sidenote, I understand sphinxcontrib-svg2pdfconverter's operation is transparent to builders, so there's no work required to "integrate" it in rinohtype.

I'm afraid I can't spend much more time on this. If you can provide a pull request to the sphinxcontrib-plantuml, I'd be happy to review it though.

**Comment by vtexier** [comment]
For plantuml extension to output pdf, `epstopdf` is required.

But `epstopdf` requires to install a lot of the latex packages. And rinoh was for me a way to avoid that.

So with rinoh:
- A contribution to `sphinxcontrib-plantuml` need to be done and accepted.
- Only bitmap png will be supported, after require a fix to `purepng` not reading plantuml png.
- pdf output is excluded as it needs latex packages so annihilate the lightweight of rinoh.

So I will go back to `latexpdf` builder for my pdf with plantuml diagrams.
Like you, sadly not more time to spend on this.

I give you the `plantuml.py` code anyway, if you want to get back to the subject one day:

```python
def rinoh_render_plantuml(self, node):
    try:
        refname, outfname = render_plantuml(self, node, 'svg')
    except PlantUmlError as err:
        _warn(self, str(err))
        raise nodes.SkipNode
    return outfname
```

And thanks for your quick and efficient feedback!

**Comment by brechtm** [comment]
Perhaps it's possible to have sphinxcontrib-plantuml use Ghostscript's ps2pdf instead? 

I'll create a ticket on sphinxcontrib-plantuml's issue tracker and point to this one, in case someone wants to add rinohtype support in the future.

Cheers!
