### ISSUE TITLE
Allow customizing the subtitle (release/version) shown on the title page

### ISSUE THREAD

**Issue by thiagocrepaldi** [brechtm/rinohtype#157]
Similar to what was reported and fixed by https://github.com/sphinx-doc/sphinx/issues/3392, the same happens for rinoh

In fact, it would be nice if users could choose whether to use 'release' or 'version' in the PDF cover and once chosen, users could customize the string for 'Release' (latex releasename property) or 'Version' string for 'version'

**Comment by brechtm** [comment]
There is currently no way to override this, which is the document's _subtitle_. Some ideas:
- Introduce a `rinoh_subtitle` configuration variable to override the default "Release {release}".
- Introduce a `rinoh_metadata` configuration variable (dict). This would also allow overriding the document's title, author and date (which are also placed on the title page).

Both of these would accept plain strings but also _StyledText_ instances.

Note to self: check what ends up in the metadata dict when rendering a reStructuredText file using rinoh.

**Comment by brechtm** [comment]
@thiagocrepaldi Would you be interested in providing a PR adding the feature? The implementation seems trivial. Please also create a unit test if you decide to tackle this.

**Comment by thiagocrepaldi** [comment]
Hi @brechtm I'd love too, but I dont understand anything about the internals of rinoh. I merely read a tutorial such as https://medium.com/@richdayandnight/a-simple-tutorial-on-how-to-document-your-python-project-using-sphinx-and-rinohtype-177c22a15b5b to create a PDF out of my sphinx setup.

I could try if I have some guidance on how to get started. I was reading some documentation, and I have to be honest in saying that it looks complex for newcomers. Lots of concepts that build on each other

**Comment by brechtm** [comment]
@thiagocrepaldi Oops. I said the implementation seems trivial, but of course I know where to start 😁. The relevant code is [here](https://github.com/brechtm/rinohtype/blob/2f60837b0c1397b12c7ade415b9e241a62f6da5c/src/rinoh/frontend/sphinx/__init__.py#L240), in the Sphinx builder. You can update the metadata dict with the value assigned to `rinoh_metadata` (to be added [here](https://github.com/brechtm/rinohtype/blob/2f60837b0c1397b12c7ade415b9e241a62f6da5c/src/rinoh/frontend/sphinx/__init__.py#L347)).

Have a look at the test cases for the Sphinx frontend [here](https://github.com/brechtm/rinohtype/blob/2f60837b0c1397b12c7ade415b9e241a62f6da5c/tests/test_sphinx.py#L79). This will likely require splitting off the code to create/modify `rinoh_document` from RinohBuilder.write_doc() into a separate function.

It would indeed be useful to include a bird's eye view of the codebase in the documentation for contributors. If you have any remarks about what is making this difficult for you at this point, that could be useful too. Thanks!

**Comment by thiagocrepaldi** [comment]
> 
> 
> @thiagocrepaldi Oops. I said the implementation seems trivial, but of course I know where to start 😁. The relevant code is [here](https://github.com/brechtm/rinohtype/blob/2f60837b0c1397b12c7ade415b9e241a62f6da5c/src/rinoh/frontend/sphinx/__init__.py#L240), in the Sphinx builder. You can update the metadata dict with the value assigned to `rinoh_metadata` (to be added [here](https://github.com/brechtm/rinohtype/blob/2f60837b0c1397b12c7ade415b9e241a62f6da5c/src/rinoh/frontend/sphinx/__init__.py#L347)).
> 
> Have a look at the test cases for the Sphinx frontend [here](https://github.com/brechtm/rinohtype/blob/2f60837b0c1397b12c7ade415b9e241a62f6da5c/tests/test_sphinx.py#L79). This will likely require splitting off the code to create/modify `rinoh_document` from RinohBuilder.write_doc() into a separate function.
> 
> It would indeed be useful to include a bird's eye view of the codebase in the documentation for contributors. If you have any remarks about what is making this difficult for you at this point, that could be useful too. Thanks!

Sorry, @brechtm I am in the middle of a sprint for release. Will get back to you soon :)
