### ISSUE TITLE
Typeface 'Noto Sans Devanagari' not installed

### ISSUE THREAD

**Issue by gour** [brechtm/rinohtype#159]
Hello,

I am very excited that development of Rinohtype is resumed!!
It's one of the reasons I've focused to use rst markup for all my writing (blog posts, articles, study notes, slide presentations, documentation...) and I'm evaluating to see if could replace need to learn/use ConTeXt.

Here is minimal example which renders Sanskrit diacritics and Devanagari:

```
\definefallbackfamily [mainface] [ss] [Noto Sans Devanagari]
   [range={devanagari,devanagariextended},
    features=devanagari-two]

\definefontfamily [mainface] [ss] [Noto Sans]

\setupbodyfont[mainface]

\starttext

ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते ।
सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते ॥ ६२ ॥

dhyāyato viṣayān puṁsaḥ
saṅgas teṣūpajāyate
saṅgāt sañjāyate kāmaḥ
kāmāt krodho ’bhijāyate

\stoptext
```

and I'm trying to typeset it using Rinoh:

```
This is a section
-----------------

ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते ।
सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते ॥ ६२ ॥

Another section
---------------
dhyāyato viṣayān puṁsaḥ
saṅgas teṣūpajāyate
saṅgāt sañjāyate kāmaḥ
kāmāt krodho ’bhijāyate
```

Here is the stylesheet which I wrote:

```
[STYLESHEET]
name=My Style Sheet
description=Small tweaks made to the Sphinx style sheet
base=sphinx

[VARIABLES]
serif=Noto Sans
sans_typeface=Noto Sans Devanagari
```

but invoking it with: `rinoh -s sanskrit.rts t.rst`

produces:

```
rinoh -s sanskrit.rts t.rst
Using the reStructuredText frontend [built-in]
rinohtype 0.4.0 (2020-03-05)  Copyright (c) Brecht Machiels
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
TeX Gyre Pagella does not include a normal medium upright font. Falling back to normal regular upright
Typeface 'Noto Sans Devanagari' not installed. Consider passing the --install-resources command line option.
```

so I wonder if, besides having all the required fonts installed on my Fedora fc32 desktop machine, I need something else in order to Rinoh recognize/use the font?

Sincerely,
Gour

**Comment by brechtm** [comment]
Thanks for the kind words! And sorry for the delay in getting back to you.

rinohtype does not (yet) look for fonts installed on the operating system. You'll need to create a python package for the font you want to use. Please take a look at [rinoh-typeface-dejavuserif](https://github.com/brechtm/rinoh-typeface-dejavuserif) for an example of how to create one. Note that you need to define an entry point in `setup.py`. Let me know if you run into any issues with this.

I would be interested to see whether rinohtype produces proper output for Sanskit (if any!), as this might require more True/OpenType features than rinohtype currently supports.

**Comment by brechtm** [comment]
Closing this stale issue. Don't hesitate to create a new comment, however!
