### ISSUE TITLE
Video fall-back

### ISSUE THREAD

**Issue by maltfield** [brechtm/rinohtype#172]
It would be awesome if rinohtype supported some system of graceful fall-back when producing PDFs from Sphinx documentation with videos.

At minimum, I imagine the video being replaced with the following text would be useful:

```
(Note: video embed placeholder. Please see <url-of-video>)
```

Ideally, the video would be replaced by an image such that that image:

1. is the video's [thumbnail image](https://www.get-youtube-thumbnail.com/) (poster/title image)
1. is overlayed with a QR code encoding the url of the embedded video.
1. has a caption explaining that the video can be accessed at `<url-of-video>`

Can you please advise on what changes (including the files/functions/hoooks/logic paths) would be required to be updated to make this a reality?

**Comment by brechtm** [comment]
As far as I know, Sphinx doesn't support embedding video's out of the box. You are using the [sphinxcontrib.youtube](https://pypi.org/project/sphinxcontrib.youtube/) extension, perhaps? You can add rinohtype support to it. See [this comment on issue 118](https://github.com/brechtm/rinohtype/issues/118#issuecomment-613582610) for instructions on how to do that. Including a link to the video in the PDF output should be relatively easy to implement.

I'm pretty sure PDF supports embedding videos. That will require downloading the video, possibly converting it to a suitable format and embedding it properly in the PDF file. I imagine that will require a lot of work.

Another interesting option would be to not directly embed the video file, but displaying it in the document, streaming it directly from YouTube (or somewhere else). This [appears to be possible as well](https://www.youtube.com/watch?v=YUvQciwfHPs), but this will be hard to implement as well, and will probably break when YouTube changes it's API.
