### ISSUE TITLE
Page size settings in the template configuration are ignored by the Sphinx frontend

### ISSUE THREAD

**Issue by brechtm** [brechtm/rinohtype#178]
The page size configured in the template configuration is always overridden, even if none of `rinoh_paper_size`, `latex_elements['paper_size']` or `latex_paper_size` are set in _conf.py_. It seems the default `latex_elements['paper_size']` value is used.

This is best fixed by addressing #77.

**Comment by alexfargus** [comment]
With the merging for #192 I believe that this can now be closed.
