### ISSUE TITLE
How to allow hypenation of first word on line?

### ISSUE THREAD

**Issue by alexfargus** [brechtm/rinohtype#188]
I have a document with a long list of path like strings. For example:

> * a/very/long/path
> * another/very/long/path

Currently when building a pdf this causes the items to run over the end of the page while printing the warning "item too long to fit on path".

I have discovered that by monkey-patching the function `Line.append_word()` to return `False` after the warning will allow the paths to be hyphenated. Whilst this works, I would prefer to implement a cleaner solution.

I assume that it is a conscious decision no to hyphenate in the case of a single string being too long to fit on the line because it is being caught and the warning issued. Therefore I assume that a PR containing the change described above would not be accepted. Is this assumption correct?

If so, I think that the next option would be to add a template configuration variable to allow to enable my desired behaviour. Is this the right approach?

**Comment by brechtm** [comment]
I think it's fine for paths to be hyphenated. Probably your paths are ` ``literal`` ` strings? In that case, hyphenation is disabled by default. See the _monospaced_ style in the [Sphinx style sheet](http://www.mos6581.org/rinohtype/sphinx_stylesheet.html?highlight=[monospaced]). I think for paths, this makes sense. However, it would be good to be able to split the path on slashes.

To this effect, a new TextStyle attribute could be introduced to specify a list of characters that are valid line breaking points, along with whether the break should occur before or after the character. Of course, no hyphen should be inserted for these cases, so it should probably not be labeled using the therm 'hyphenation'.

Alternatively, it might just work to manually insert [zero-width spaces](https://en.wikipedia.org/wiki/Zero-width_space) at the locations where you would allow line breaks, but I haven't tested this. This could also be a good approach to implementing support for the TextStyle attribute discussed above.

**Comment by alexfargus** [comment]
Thanks for the hints. I will take a look.
