### ISSUE TITLE
Multiple source documents

### ISSUE THREAD

**Issue by finngaida** [brechtm/rinohtype#196]
I'd like to render multiple Commonmark source files into the same output document, but couldn't find any documentation/examples on that. What's my best option for this?

**Comment by brechtm** [comment]
CommonMark doesn't seem to offer this functionality. There's some discussion on it here: [Transclusion or including sub-documents for reuse](https://talk.commonmark.org/t/transclusion-or-including-sub-documents-for-reuse/270/13).

If you're writing documents that are more complex than a simple readme, I recommend you use reStructuredText instead, which offers more features and has a much more clearly defined syntax. reStructuredText is not without issues, but I'm still convinced it is the better option. See [Why You Shouldn’t Use “Markdown” for Documentation](https://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/) for some motivation.

**Comment by brechtm** [comment]
Closing this issue now, but you can still add comments if you have follow-up questions.
