### ISSUE TITLE
The Into Pdf seems to be broken

### ISSUE THREAD

**Issue by michaelko** [brechtm/rinohtype#2]
At last it does not look like i think it should on my computer in neither evince nor firefox. I'm talking about [this file](http://www.mos6581.org/files/intro_template.pdf)

2 screenshots: https://imgur.com/ha4J3XO,ykxSFo6#0

**Comment by frol** [comment]
FYI, PDF.js in Firefox 43.0.1 (Arch Linux) renders the intro_tempate.pdf correctly! However, Evince 3.18.2 (poppler 0.39.0) still has the bug and looks just like on the screenshot provided above. You seem to understand the issue better, so could you please file the bug on [Poppler's bugtracker](https://bugs.freedesktop.org/buglist.cgi?bug_status=__open__&product=poppler)?

**Comment by brechtm** [comment]
Yes, I noticed recent versions of PDF.js do indeed render RinohType PDFs correctly. Didn't think of updating this issue though, so thanks!

Poppler bug reported: https://bugs.freedesktop.org/show_bug.cgi?id=93559

**Comment by brechtm** [comment]
PDF.js fixed this problem somewhere between v1.0.1149 and v1.1.3.
Possibly fixed by https://github.com/mozilla/pdf.js/pull/5770

**Comment by brechtm** [comment]
The [poppler bug](https://bugs.freedesktop.org/show_bug.cgi?id=93559) has been fixed.

**Comment by frol** [comment]
I can confirm that the PDF works fine now with Poppler 0.41 release!

**Comment by brechtm** [comment]
Thanks for verifying frol!
