### ISSUE TITLE
Example output link in the README is a 404

### ISSUE THREAD

**Issue by jdillard** [brechtm/rinohtype#232]
It looks like the example output link on line 89 of the README is a 404: https://github.com/brechtm/rinohtype/edit/master/README.rst#L89

(Arg, GitHub won't let you link directly to lines on RST files...)

I tried to see if it moved, but Google couldn't find anything: https://www.google.com/search?q=filetype%3Apdf+site%3Amos6581.org

**Comment by brechtm** [comment]
Thanks for reporting this, @jdillard!
