### ISSUE TITLE
Image Substitutions do not respect the width I am setting

### ISSUE THREAD

**Issue by Tanichezini** [brechtm/rinohtype#254]
**What happens:**
I have created image substitutions like for example:

.. |edit| image:: images/buttons/edit.png
   :width: 20px

I placed them in sentences in my document and since they appeared too big I tried to play around with the image size. However it does not seem to make any difference in the PDF documents I created, while when I run the html version of the document the icons are changed in size according to my desire.

**How to reproduce:**
Create image substitutions specifying the size of the image. Run Sphynx Rinoh to create a PDF document and see that the size of the icons seem not to be affected by the settings of the size parameters.

What Am I expecting:
I am expecting the size of the icons in the PDF document to respect the size I have set.

**Comment by Tanichezini** [comment]
Hi Brecht. 
Thank you for considering my observation. Since this is my first contribution I was wondering what happens next. 
Cheers Luisa

**Comment by brechtm** [comment]
> Thank you for considering my observation. Since this is my first contribution I was wondering what happens next.

This fix will be included with 0.5.3. It's been a while since the last release, so I'll try to get 0.5.3 out soon.

P.S. Many thanks for sponsoring! ❤️

**Comment by brechtm** [comment]
I forgot to mention that you can always install the in-development version by installing from git:

    pip install git+https://github.com/brechtm/rinohtype.git
