### ISSUE TITLE
Render citation definitions in the body of the document

### ISSUE THREAD

**Issue by alexfargus** [brechtm/rinohtype#269]
After fixing #262 my next task is to position the definition in the body of the document. Currently they are rendered as footnotes however according to https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#citations "Citations may be rendered separately and differently from footnotes."

I think that this would make is more consistent with the behaviour of the sphinx html output and I also think this is a prequisite for implementing a bibliography section.

This is an example of what I am proposing is [citations.pdf](https://github.com/brechtm/rinohtype/files/6665397/citations.pdf)

@brechtm Would you want this change in rinoh?

**Comment by brechtm** [comment]
Yes, that would be great to have!

> Would you want this change in rinoh?

Do you mean the rinoh command line tool specifically? Yes, I would prefer to have this functionality both in the Sphinx builder and _rinoh_.

Thinking out loud: we could add _target_ style attribute to `NoteMarkerStyle`, which could accept _footer_ and _section_, or something along those lines. And introduce a `Notes` class (~ `Index`) to display all notes/citations. This class could be used for both a Bibliography and "End Notes" (as an alternative to footnotes).
