### ISSUE TITLE
Incompatibility with sphinx: 'RinohBuilder' uses deprecated methods from the Sphinx's 'Builder' class

### ISSUE THREAD

**Issue by inethappy** [brechtm/rinohtype#276]
* rinohtype version: 0.5.3
* Sphinx version: 4.1.1
* Python version: >= 3.7.2
* operating system: Windows

![image](https://user-images.githubusercontent.com/45874056/125906585-e15fab6b-e43e-4db0-a860-afda332014a0.png)

The link to the sphinx doc with  the deprecated APIs: https://www.sphinx-doc.org/en/master/extdev/deprecated.html

![image](https://user-images.githubusercontent.com/45874056/125906796-a1e6d1fc-1fd8-4f64-9a3c-faa5e14f193b.png)

**Comment by brechtm** [comment]
Thanks for reporting! However, as far as I can see, we have been using the Sphinx logging API since rinohtype 0.4.0 (commit 4333d4b54fb5f543b673e0f927551cbe03a9f66c). Please double-check that you are running rinohtype 0.5.3.
