### ISSUE TITLE
'Section' has no attribute 'node_location' when using mermaid directive

### ISSUE THREAD

**Issue by markhoneth** [brechtm/rinohtype#290]
I'm not familiar with the inner workings of Sphinx and rinohtype so I'd really appreciate some help with this. 
HTML output works fine, but I'm getting the following exception when I try to build the PDF with rinohtype: 

1. ```
    ...
    Traceback (most recent call last):
         File "c:\programdata\anaconda3\envs\docs\lib\site-packages\rinoh\frontend\__init__.py", line 27, in map_node
            return cls._mapping[node_name.replace('-', '_')](node, **context)
    KeyError: 'mermaid'
    
    During handling of the above exception, another exception occurred:
    
    ...
    Traceback (most recent call last):
      File "c:\programdata\anaconda3\envs\docs\lib\site-packages\rinoh\frontend\__init__.py", line 29, in map_node 
          filename, line, node_name = cls.node_location(node)
    AttributeError: type object 'Section' has no attribute 'node_location'
    ```
    See the [attachment](https://github.com/brechtm/rinohtype/files/7102276/sphinx-err-xjltm7lq.log) for the full trace.

2. I have a simple mermaid directive in my content:
    ```.. mermaid:: data/gantt_chart.mmd```
    If I remove the directive, the PDF is generated without issues.

    My `conf.py` is using the mermaid extension (without the CLI):
    ```
    extensions = [
                 #...                        
                 'sphinxcontrib.mermaid',
                ]
    ```


### System Info
* rinohtype version: `0.5.3`
* Sphinx version: `4.0.2`
* Python version: `3.9.5`
* Windows version: `10.0.19043`

**Comment by brechtm** [comment]
sphinxcontrib-mermaid would need to add support for the rinoh builder for this to work. This extension could possibly be made independent of specific builders by using an approach described in the comments to #201.

Closing as this isn't a bug in rinohtype. Discussion is still allowed, of course.
