### ISSUE TITLE
support markdown, e.g. the one used by authorea

### ISSUE THREAD

**Issue by yarikoptic** [brechtm/rinohtype#3]

**Comment by brechtm** [comment]
Until a Markdown frontend is available, you can use [Pandoc](http://pandoc.org) to convert Markdown to reStructuredText.

**Comment by brechtm** [comment]
This might be less work than anticipated, since Markdown can be parsed into a docutils tree:
http://thread.gmane.org/gmane.text.docutils.user/7407

**Comment by AndydeCleyre** [comment]
I'd like to add to this topic a link to a developing markdown variant called Markua, since it has publishing tasks in mind: http://markua.com/

**Comment by brechtm** [comment]
264f4c0 includes a CommonMark frontend based on [recommonmark](https://github.com/rtfd/recommonmark).

**Comment by brechtm** [comment]
@AndydeCleyre Since Markdown is so fragmented, I'm not going to spend time to write a parser for any one flavor. If a parser would exists that parses Markua into a docutils document tree, it would be trivial to support in RinohType though.
