### ISSUE TITLE
Please delete

### ISSUE THREAD

**Issue by BobDenny** [brechtm/rinohtype#329]
Please delete this.  I found the full docs.

**Comment by brechtm** [comment]
Hi @BobDenny. Sorry for the late response; I have been busy with other things lately, but I will try to make a new release soon (but not before my two-week vacation). 0.5.4 is the current in-development version for which the docs are also accessible online. The documentation does need some TLC to make it more accessible however.
Good to hear you were able to figure things out. And many thanks for the sponsorship!
