### ISSUE TITLE
Is the pip install route broken?

### ISSUE THREAD

**Issue by matthew-ivre** [brechtm/rinohtype#331]
I used pip to install rinohtype. I now have version 0.5.3.

This version doesn't include the update from https://github.com/brechtm/rinohtype/pull/270, so each time I tried to generate an output, I got a "typeerror expected string or bytes-like object" error. I manually made that update on my local files, and it resolved the error.

I guess I'm missing other important updates. Is it possible to create a new release for pip? Or should I get the latest updates through some other means? Thanks.

**Comment by brechtm** [comment]
I'm planning to finally release 0.5.4 in the coming days. Hopefully, this time it will actually materialize! 🤞

I've also added instructions to the README on how to install the current development version:

> If you want to have access to bug fixes and features that are not available in
> a release, you can install the current development version::
> 
>     pip install https://github.com/brechtm/rinohtype/archive/refs/heads/master.zip
