### ISSUE TITLE
Title from index.rst file is not generating in PDF

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [brechtm/rinohtype#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

-------------------

Test content here Test content here Test content hereTest
content hereTest content hereTest content here Test
content here Test content hereTest content hereTest
content hereTest content hereTest content here Test
content hereTest content hereTest content hereTest
content here Test content hereTest content hereTest
content hereTest content here.

### Source files

Welcome to Test project's documentation!
========================================

Test content here Test content here Test content hereTest content hereTest content hereTest content here
Test content here
Test content hereTest content hereTest content hereTest content hereTest content here
Test content hereTest content hereTest content hereTest content here
Test content hereTest content hereTest content hereTest content here.

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   testfile1
   testfile2

### Versions

```text
rinoh 0.5.4 (2022-06-17)

sphinx-build 3.2.1

Python 3.8.10
```

**Comment by brechtm** [comment]
Where are you expecting the title of the [root_doc](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-root_doc) to appear? On the title page or in front of the body text (after the table of contents)?

Perhaps a `None` value (not very intuitive, though) for _title_ in the _rinoh_documents_ dicts could instruct rinohtype to use the title of the root document. This would be similar to an "empty" (whatever that means) title value in [latex_documents](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_documents)?
