### ISSUE TITLE
Please test with Docutils 0.19b1

### ISSUE THREAD

**Issue by AA-Turner** [brechtm/rinohtype#340]
Hi,

We've just released Docutils 0.19b1, and intend to release 0.19 final on 05/07/2022 (a week on Tuesday). Please would you test with the pre-release, and raise any issues to me either on this issue or on the Docutils tracker?

- The release notes are at: https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-19b1-2022-06-21
- The detailed change history is at: https://docutils.sourceforge.io/HISTORY.html#release-0-19b1-2022-06-21
- You can install 0.19b1 with `python -m pip install --pre "docutils==0.19b1"` or install Docutils' master with `python -m pip install "git+https://repo.or.cz/docutils.git#subdirectory=docutils"`.

Thanks,
Adam

**Comment by brechtm** [comment]
Thanks for the heads-up, Adam!

I ran the regression tests against docutils 0.19b1 and observed to issues.

P.S. [CI](https://github.com/brechtm/rinohtype/actions) runs these tests automatically against new docutils releases (including pre-releases like this). Of course, a new release is only tested when a new rinohtype commit is pushed followin the release.

**Comment by AA-Turner** [comment]
Thanks Brecht!

A
