### ISSUE TITLE
Another exception error.....

### ISSUE THREAD

**Issue by techauthoruk** [brechtm/rinohtype#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Sphinx or rinoh output

```text
Running Sphinx v5.1.1
loading pickled environment... failed
failed: No such config value: rinoh_documents
building [mo]: targets for 0 po files that are out of date
building [rinoh]: all documents
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [100%] trouble
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing manual... index legal history preface description safety prepare operation maintenance trouble disposal appxI appxII appxIII appxIV appxV appxVI glossary signs resolving references...
rinohtype 0.5.5 (in development)  Copyright (c) Brecht Machiels and contributors
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
rendering...

Exception occurred:
  File "/home/mark/.venv/lib/python3.10/site-packages/rinoh/text.py", line 146, in copy
    raise NotImplementedError
NotImplementedError
The full traceback has been saved in /tmp/sphinx-err-h_gkfe13.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: rinoh] Error 2
```

### Source files

I'm thinking this is another issue relating to tables, but not sure (I haven't included any reST that should break things) did the previous table fix get included?

Error log:

[sphinx-err-h_gkfe13.log](https://github.com/brechtm/rinohtype/files/9831290/sphinx-err-h_gkfe13.log)

### Versions

```text
rinohtype 0.5.5 (in development)
Sphinx 5.1.1
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

**Comment by techauthoruk** [comment]
...also, I don't know why there is the:

```bash
loading pickled environment... failed
failed: No such config value: rinoh_documents
```

errors....

**Comment by techauthoruk** [comment]
OK,

So the issue wasn't tables...it was down to the `index` directive again.

If you include `index` in any heading, you get the issue. So, although for main headings

```bash
:index:`A heading`
##############
```
there isn't a problem, **but** using `index` in any other form of heading or sub-heading causes the exception:

```bash
Subtitle -- Asterisks
*********************

Section -- Equal Signs
======================

Subsection -- Hyphens
---------------------

Subsubsection -- Circumflex
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Paragraph -- Double Quotes
"""""""""""""""""""""""""""""""
```

I have just tried using

```bash
####################################
Part -- Number Signs above and below
####################################

with overline, for parts

************************************
Chapter -- Asterisks above and below
************************************

with overline, for chapters
```
and the exception occurs with these heading formats as well. Over to you @brechtm for a fix!

**Comment by techauthoruk** [comment]
@brechtm 

Any timescale on when this might be fixed? Its not an issue as I am aware of the problem, but would be good to have a fix (sometimes you have to index a title/subtitle)

**Comment by brechtm** [comment]
I am failing to reproduce this. Please make sure that you're running the latest rinohtype master version. Otherwise, can you share your Sphinx project, or a minimal one that reproduces the issue?

**Comment by techauthoruk** [comment]
Still crashes with my install, even with a minimal config.

I'm only including this on a single page:

```bash
##################
:index:`Heading` 1
##################

==================
:index:`heading 2`
==================


:index:`Some indexed` text
==========================


Unindexed
---------

:index:`Indexed`
^^^^^^^^^^^^^^^^
```
Which results in: 
Exception occurred:
  File "/home/mark/.venv/lib/python3.10/site-packages/rinoh/text.py", line 146, in copy
    raise NotImplementedError
NotImplementedError

If I remove the index entries, all builds correctly. As far as I know, I'm using the current master of rinoh (0.5.5 in development). I've attached the files to see if it helps...
[test.zip](https://github.com/brechtm/rinohtype/files/9868193/test.zip)

**Comment by brechtm** [comment]
Thanks for the minimal project. I had to restore the `:index:` role annotations in _test.rst_, but the PDF builds without a problem! Try to uninstall and reinstall rinohtype master in the virtual environment:
´´´
pip install https://github.com/brechtm/rinohtype/archive/refs/heads/master.zip
´´´

If that doesn't help, perhaps the virtual environment has become corrupted. Try deleting it and recreating it.

**Comment by techauthoruk** [comment]
@brechtm Reinstalling from the master version sorted that (although it did uninstall my current version of Sphinx!). All sorted now - thank you so much! I will close this off now.
