### ISSUE TITLE
Problems after updating Sphinx

### ISSUE THREAD

**Issue by techauthoruk** [brechtm/rinohtype#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

PDF appears ok

### Source files

After updating my install to the latest Sphinx version, I get these errors when running `make rinoh`:

```bash
Running Sphinx v6.0.0b3
making output directory... done
loading pickled environment... failed
failed: Can't get attribute '_stable_repr_object' on <sphinx.deprecation._ModuleWrapper object at 0x7f32a02e6080>
```
as far as I can tell, the pdf appears to be created successfully, so this may be a trivial issue.

### Versions

```text
rinohtype 0.5.5 (in development)
Sphinx 6.0.0b3
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

**Comment by brechtm** [comment]
I think this one is not related to rinohtype. Sphinx caches some data in a pickle file. Sometimes, if Sphinx internals change, the new version cannot use the pickle file created by the older version.
