### ISSUE TITLE
Part of image missing....

### ISSUE THREAD

**Issue by marklees-seab** [brechtm/rinohtype#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

Here is a pdf version of my image (created in Acrobat):

[cover.pdf](https://github.com/brechtm/rinohtype/files/9878120/cover.pdf)

And here is the cover page image:

![cover](https://user-images.githubusercontent.com/113504843/198251325-f1485b41-6368-44ab-a408-c248a58c84a7.png)

Here is a partial screenshot after generating the pdf from Sphinx:

![image](https://user-images.githubusercontent.com/113504843/198251787-64dcf4ee-67d9-4881-b3e1-daa6bf6689e8.png)

I'm at a total loss....how can the CE mark etc, be present in the image and a pdf created in Acrobat, but be missing in the rinoh output? The image is a flat file with only a single layer, so I am totally bemused as to this behaviour. Any thoughts?

### Source files

See above

### Versions

```text
no change
```

**Comment by marklees-seab** [comment]
I have run `make clean` just to be sure, but this makes no difference. Is the original image being cached somewhere I am not aware of? I created a new jpeg image and tried this, but the same thing happened (and if I deleted the image, rinoh came up with an error saying it couldn't find the image and built the pdf without it).

I'm totally flummoxed!

**Comment by techauthoruk** [comment]
Duh! Who would have thought it! The problem **WAS** that the image had more than one layer. When I re-edited the image in Photoshop and flattened the image, all works as it should.

You live and learn!

**Comment by marklees-seab** [comment]
Closing this off
