### ISSUE TITLE
TypeError: Can't instantiate abstract class DynamicRinohDistribution with...

### ISSUE THREAD

**Issue by BobDenny** [brechtm/rinohtype#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Sphinx or rinoh output

```text
(.venv) D:\dev\astro\ASCOM Alpaca\Alpyca\docs>make html
Running Sphinx v5.3.0

Exception occurred:
  File "D:\dev\astro\ASCOM Alpaca\Alpyca\.venv\lib\site-packages\rinoh\resource.py", line 187, in <module>
    _DISTRIBUTION = DynamicRinohDistribution()
TypeError: Can't instantiate abstract class DynamicRinohDistribution with abstract methods locate_file, read_text
The full traceback has been saved in C:\Users\ROBERT~1.DEN\AppData\Local\Temp\sphinx-err-5zzmd_z9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### Source files

https://github.com/ASCOMInitiative/alpyca

Clone this, open shell into the virtual environment, type  make html. By the way this identical message happens on Linux, so youj can clone it to a Linux machine though in my report it is Windows. Only the path changes, the substance of the error is identical.

Also I did install 0.5.5 from your GitHub as recommended above.

### Versions

```text
(.venv) D:\dev\astro\ASCOM Alpaca\Alpyca\docs>rinoh --versions
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\dev\astro\ASCOM Alpaca\Alpyca\.venv\Scripts\rinoh.exe\__main__.py", line 4, in <module>
  File "D:\dev\astro\ASCOM Alpaca\Alpyca\.venv\lib\site-packages\rinoh\__init__.py", line 41, in <module>
    from . import resource
  File "D:\dev\astro\ASCOM Alpaca\Alpyca\.venv\lib\site-packages\rinoh\resource.py", line 187, in <module>
    _DISTRIBUTION = DynamicRinohDistribution()
TypeError: Can't instantiate abstract class DynamicRinohDistribution with abstract methods locate_file, read_text
```

**Comment by BobDenny** [comment]
On Linux:

```
(.venv) pi@rpi1:~/Documents/alpyca/docs $ rinoh --versions
Traceback (most recent call last):
  File "/home/pi/Documents/alpyca/.venv/bin/rinoh", line 5, in <module>
    from rinoh.__main__ import main
  File "/home/pi/Documents/alpyca/.venv/lib/python3.9/site-packages/rinoh/__init__.py", line 41, in <module>
    from . import resource
  File "/home/pi/Documents/alpyca/.venv/lib/python3.9/site-packages/rinoh/resource.py", line 187, in <module>
    _DISTRIBUTION = DynamicRinohDistribution()
TypeError: Can't instantiate abstract class DynamicRinohDistribution with abstract methods locate_file, read_text
```

**Comment by BobDenny** [comment]
I tried this outside the virtual environment .venv on Linux and and I get this:
```
pi@rpi1:~ $ rinoh --versions
rinohtype 0.5.5 (in development)
Sphinx 4.5.0
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Linux-5.15.76-v8+-aarch64-with-glibc2.31
```
This started happening to me when I use Poetry to update dependencies for my project (in the .venv). So this is "caused"  by a newer dependency. Let me try to run this down.

**Comment by matthijsgeers-riscure** [comment]
I also ran into this issue, after updating all dependencies in the venv of my project. Downgrading to rinohtype 0.5.3 solved the issue for me, though I haven't investigated why yet. I'm running Python 3.8.10

**Comment by brechtm** [comment]
I cloned the alpyca repository and did a `poetry install`. That didn't install Sphinx, rinohtype or the other dependencies required for building the docs. Installing them manually using pip, `make html` and `make rinoh` work fine for me. These are the versions of the packages installed:

```
$ rinoh --versions
rinohtype 0.5.4 (2022-06-17)
Sphinx 5.3.0
Python 3.10.1 (main, Dec 11 2021, 18:34:42) [Clang 13.0.0 (clang-1300.0.29.3)]
macOS-12.6-x86_64-i386-64bit
```

I was able to reproduce the issue by installing importlib-metadata. I'm afraid that it's API changed again 😢  If you're running Python 3.9+, I think you should be able to uninstall it from your virtualenv.

Related: sphinx-doc/sphinx#10157

**Comment by calve** [comment]
Hi ! running into this aswell. Shouldn't we pin `importlib_metadata` to a version `< 6` at https://github.com/brechtm/rinohtype/blob/370b5a54ae4d06cfc3a41ccbb21c86945f91783b/pyproject.toml#L90 and cut a release ?


For lost readers, I fixed my build by adding 

```
importlib_metadata==5.2.0
```

in its requirements.txt

**Comment by brechtm** [comment]
> Shouldn't we pin `importlib_metadata` to a version `< 6` at

I'm hesitate to set version constraints on dependencies, since it could cause conflicts with other packages requiring a newer version in the future. I added NotImplementedError-throwing implementations for those abstract methods to avoid the crash.

**Comment by BobDenny** [comment]
I am still wrestling with this. Windows 10, Python (plain vanilla) 3.11.1, Sphinx 6.1.3, rinohtype 0.5.4, I get the error. In order to get past it I had to roll rinohtype back to 0.5.3, and also sphinx back to 5.3.0. After that the DynamicRinohDistribution error went away, and now I am left with this
```
Running Sphinx v5.3.0

Exception occurred:
  File "C:\Program Files\Python311\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```
for making either rinoh or html. Removing `'rinoh.frontend.sphinx'` from the conf.py `extensions` allows building html normally so this is related to rinoh. I apologize I am no Python guru, but it looks like somehow a bad regex is being used. 

What am I supposed to do? I tried @matthijsgeers-riscure solution (I already have Python 3.11.1), rinohtype 0.5.3 and Sphinx 6.1.1 fails here with DynamicRinoh....

**Comment by BobDenny** [comment]
I finally found the critical element in this. If importlib-metadata is upgraded to 6.0.0 it will cause this error to occur. By downgrading this package to 4.11.4 everything works on Windows and Linux, Python 3.7, 3.9, and 3.11. **This is clearly where the problem is**.  I have upgraded Sphinx to 6.1.3 and rinohtype to 0.5.4 (their latest versions) and HTML and PDF building works perfectly.  I found this by comparing packages one after another with one of my old test systems on which I could build using the global site packages (thank goodness).

**Comment by brechtm** [comment]
@BobDenny (in response to your removed comments) Great to read that you've been able to get around the problem!

I wasn't very explicit in my last comment, but this problem was fixed in rinohtype and could have saved you some trouble. The fix is not yet available in a release, but it's easy enough to install the current development version (as [described in the README](https://github.com/brechtm/rinohtype#getting-started)):
```console
pip install https://github.com/brechtm/rinohtype/archive/refs/heads/master.zip
```

P.S. There's no need to remove your comments. They could help other souls running into this issue :-)

**Comment by BobDenny** [comment]
@calve nailed it. I had to revert importlib-metadata to a older version, and make a note to myself to avoid ever updating it to 6..x.  I'm not big on development/experimental stuff. I'll watch for a production version. Thank you for the help.

**Comment by brechtm** [comment]
You shouldn't be too hesitant to run the development version. At this point, there's not much difference between the releases and the development version. They are more or less just development snapshots at arbitrary points in time.

**Comment by aut0** [comment]
Is my understanding correct that "pip install rinohtype" is broken until the fix is released?

**Comment by brechtm** [comment]
@aut0 Yes, that is correct. And thank you for the reminder, I really should make a new release! :-)

**Comment by brechtm** [comment]
@aut0 [Version 0.5.5](https://github.com/brechtm/rinohtype/releases/tag/v0.5.5) has finally landed!
