### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by zopyx** [brechtm/rinohtype#4]
While reviewing your proposal for EuroPython 2014 I came the following installation problem:

Suxmac-2:rinohtype ajung$ bin/python setup.py install
Attempting to get version number from git...
fatal: No names found, cannot describe anything.
Assume we are running from a source distribution.
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    with open(VERSION_FILE) as version_file:
IOError: [Errno 2] No such file or directory: 'rinoh/version.py'

I don't think that it is of advantage writing a proposal for a module that can not be installed properly.

**Comment by brechtm** [comment]
RinohType is now available from PyPI
