### ISSUE TITLE
KeyError: 'desc_sig_space'

### ISSUE THREAD

**Issue by nicorenard** [brechtm/rinohtype#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Sphinx or rinoh output

```text
Hello, can you help me with this problem when using rinoh ?
I'm using the sphinx command : 'make rinoh' with the sphhinx build module
here is the last line of the log file : 

Traceback (most recent call last):
  File "c:\users\nrenard\pycharmproject\pythonproject\visiopompe2\venv\lib\site-packages\rinoh\frontend\__init__.py", line 27, in map_node
    return cls._mapping[node_name.replace('-', '_')](node, **context)
KeyError: 'desc_sig_space'

During handling of the above exception, another exception occurred:
 File "c:\users\nrenard\pycharmproject\pythonproject\visiopompe2\venv\lib\site-packages\rinoh\frontend\__init__.py", line 30, in map_node
    raise NotImplementedError("{}:{} the '{}' node is not yet supported "
NotImplementedError: None:None the 'desc_sig_space' node is not yet supported (rinoh.frontend.sphinx.nodes)

The complete report is given. 
Thanks for the help.

Regards,
Nico
```

### Source files

[sphinx-err-77tc5nzx.log](https://github.com/brechtm/rinohtype/files/12069508/sphinx-err-77tc5nzx.log)

### Versions

```text
rinohtype 0.5.4 (2022-06-17)
Sphinx 6.2.1
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
```

**Comment by brechtm** [comment]
I haven't been able to reproduce the issue; _desc_sig_space_ seem to be converted to a regular inline text node before they reach rinohtype in my tests.

Try to add the following to the top of your _conf.py_ to see whether this fixes it:
```python
from rinoh.frontend.rst import DocutilsInlineNode

class Desc_Sig_Space(DocutilsInlineNode):
    pass
```

A minimal project that triggers the issue would still be helpful.

**Comment by nicorenard** [comment]
Hello,

Thank you for your time.
It's working now. everything is perfect. thanks ! :)
Also, i'm using django and just to know , in the _conf.py_ , if I take off this code line : 

`import django
# Setup Django
os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings'
django.setup()`

rinoh work whithout you code but not the html version who become empty with theme used ( sphinx_rtd_theme for example). But that's another issue :)

I will try to give you a minimal project as quick I can. in a next reply.
[conf.zip](https://github.com/brechtm/rinohtype/files/12091850/conf.zip)

Thanks again for you time.
