### ISSUE TITLE
Hyphenating a word across two pages concatenates the word part to the next one

### ISSUE THREAD

**Issue by th0mr** [brechtm/rinohtype#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

I'm getting some unusual PDF output when a word within a paragraph is split over two pages.

When the second half of the word is moved onto the next page, no space is put between that second half of the word and the next word in the paragraph.

![image](https://github.com/brechtm/rinohtype/assets/87852659/3f5fdc87-4f28-4e49-b1bb-d3b1b0c3154a)
^ the word absolutely is split in two, the second half of the word gets attached to the next word in the sentence "terribly"

For this to happen, the word has to be the final word of a line and it must be hyphenated onto the next page.

Is there some option I can enable or to avoid this, or is this a bug?

I've attempted looking at the code to propose a solution but I got a bit lost. The closest I got was around typeset_line in ParagraphBase (https://github.com/brechtm/rinohtype/blob/master/src/rinoh/paragraph.py#L843) This looked vaguely like relevant code for hyphenation across a page, but I'm not familiar enough with the code as a whole to know where to go from here.

### Source files

**Reproduction of the issue** - [document zip](https://github.com/brechtm/rinohtype/files/12805865/hyphenation_issue_repro_basic.zip)

The built PDF is in the "build" folder

The PDF was generated with: `python -m sphinx -M rinoh ./source ./build`

### Versions

```text
rinohtype 0.5.4 (2022-06-17)
Sphinx 7.1.2
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
```

**Comment by brechtm** [comment]
Thanks for the minimal project! You are in luck, since I recently fixed this issue. 😄 
Please [install the current development version](https://github.com/brechtm/rinohtype#getting-started), which should be as stable as the latest release.

**Comment by th0mr** [comment]
Brilliant! I've just updated to the latest version and its working.

I'll close this issue. Thanks for your hard work! 😄
