### ISSUE TITLE
Sphinx :ref: references render to section number instead of title

### ISSUE THREAD

**Issue by BobDenny** [brechtm/rinohtype#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

[alpyca.pdf](https://github.com/user-attachments/files/17356498/alpyca.pdf)

### Source files
this in one document
```
:ref:`async_faq`
```
should render with this in another

```
.. _async_faq:

How can I tell if my asynchronous request failed after being started?
---------------------------------------------------------------------
```

with the title "How can I tell if my asynchronous request failed after being started?" but instead, it renders with the link "Section 7.1". There are 70 examples in the attached PDF.  HTML is rendering per the spec. 

See Sphinx docs [Cross-Referencing Arbitrary Locations](https://www.sphinx-doc.org/en/master/usage/referencing.html#cross-referencing-arbitrary-locations). Sphinxbuild indeed makes links with the title and not the section number. 

### Versions

```text
rinohtype 0.5.5 (2024-07-13)
Sphinx 7.2.6
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
```

**Comment by brechtm** [comment]
rinohtype cross-references sections in the style traditionally used for print. Sphinx's default output format is HTML, and it tends to forget considering print output. See this question on StackOverflow for how you can adjust this to your liking: https://stackoverflow.com/questions/68571864/rinohtype-link-text-is-section-3-1-instead-of-the-text-specified-in-the-link-o

See also issue #244

**Comment by BobDenny** [comment]
OMG this
```
[linked reference]
type = custom
```
in my stylesheet fixed it. **THANK YOU** there is no hope I could have figured this out. I had given up.
