### ISSUE TITLE
:numref: not generating reference

### ISSUE THREAD

**Issue by Marttico** [brechtm/rinohtype#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

I'm currently trying to automatically number my figure captions in my document using ``:numfig:``. I've followed Sphinx's [numref](https://www.sphinx-doc.org/en/master/usage/referencing.html#role-numref) documentation, which generates the following.

![Screenshot 2024-11-29 165309](https://github.com/user-attachments/assets/d889c22a-f124-4c5c-96a5-4e5272712db2)

I'm not sure whether this is a bug, or user error. I just cannot seem to find any solution online.

### Source files

I cannot share the entire source code directly. Here's a snippet of the code that's generating this issue.

```
.. _testRef:

.. figure:: images/ot-primer-roles.png
   :width: 200


Figure :numref:`Image of Sphinx (Fig. %s) <testRef>`:
```

### Versions

```text
$ rinoh --versions
rinohtype 0.5.6 (in development)
Sphinx 8.1.3
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

**Comment by brechtm** [comment]
Could it be that you're rendering this using `rinoh`? The _numref_ role is provided by Sphinx, so it cannot be rendered by `rinoh` which only supports whatever docutils supports.

**Comment by Marttico** [comment]
> Could it be that you're rendering this using `rinoh`? The _numref_ role is provided by Sphinx, so it cannot be rendered by `rinoh` which only supports whatever docutils supports.

Yes, I'm currently using the rinoh command to render it. I have considered porting my entire report to sphinx, however I couldn't find anything about this online.

Thanks for the response!
