### ISSUE TITLE
It is impossible to verbally communicate the name without commentary regarding the spelling.

### ISSUE THREAD

**Issue by AndydeCleyre** [brechtm/rinohtype#5]
Where does "rinoh" come from? In English at least, it is impossible to tell someone the name of this program without adding explanations regarding the spelling, and expect the listener to know how to spell it.

**Comment by brechtm** [comment]
RinohType sounds like [Linotype](https://en.wikipedia.org/wiki/Linotype_machine), and contains "Python" spelled backwards. Yes, I thought that was very clever when I thought of it :)
Additionally, RinohType is not too close to any existing word, so it is easy to google. But you are correct that this makes it less convenient for passing on orally.

I'm not convinced this is a good name for the project, so if you can suggest a better one, please do.

**Comment by AndydeCleyre** [comment]
Ah, well if you don't mind disfiguring a backwards python, it could simply become RhinoType.

- It still sounds like "linotype"
- It is spelled as the two words it sounds like
- It has an animal in it, though not a snake anymore

**Comment by brechtm** [comment]
Sorry, I've considered "RhinoType" before, but dismissed it. If the backwards Python has to go, I'd opt for something shorter and catchier.

**Comment by AndydeCleyre** [comment]
Hi, will there be a new name for the project, or is it settled as RinohType?

**Comment by brechtm** [comment]
For now, I'll keep the name "RinohType". It might change in the future, but I have no concrete plans at the moment.
