### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by davidedelvento** [brechtm/rinohtype#58]
Maybe related with issue #57 -- it would help if `http://www.mos6581.org/rinohtype/quickstart.html` had the PDF which is supposed to be generated by running `rinoh demo.txt`

**Comment by brechtm** [comment]
The [introduction section](http://www.mos6581.org/rinohtype/intro.html) in fact links to this PDF.

**Comment by brechtm** [comment]
It would be a good idea to add a FAQ section. A first entry could be about "empty" PDFs produced by rinohtype.

**Comment by davidedelvento** [comment]
Well, good about that -- but the problem is that http://www.mos6581.org/rinohtype/quickstart.html does mention a `demo.pdf` file which is red (no link). It would be good to have http://www.mos6581.org/rinohtype/_downloads/demo.pdf linked from the quickstart

**Comment by brechtm** [comment]
You are right. It might as well link to the demo.pdf. I'll do that.
