### ISSUE TITLE
Logo in fron page is bigger than in Latex

### ISSUE THREAD

**Issue by pcav** [brechtm/rinohtype#60]
See files sent privately.

**Comment by brechtm** [comment]
rinohtype only roughly copies Sphinx's LaTeX builder output. You can control the size of the title page logo by overriding the options for the [_title page logo_](http://www.mos6581.org/rinohtype/api/style.html#the-default-matcher) style in your style sheet.

**Comment by pcav** [comment]
Thanks. What is strange to me is that with the same input the logo has a reasonable size in the LaTEX output.

**Comment by brechtm** [comment]
Ah, I see that the Sphinx style sheet stretches the image to fill the width. LaTeX probably displays the image at the original size. You can set `width = none` for the _title page logo_ style to prevent stretching the image to the width.

See [my fork of the Lizmap documentation](https://github.com/brechtm/lizmap-documentation/commits/rinohtype) for how to specify a custom template configuration and style sheet. I noticed there's a bug with the right-aligned title image logo (the line above it) which I'll address in a next release.

**Comment by pcav** [comment]
I understand. However, IMHO the default in rinoh should mimic that of Sphinx, to act as a drop-in replacement.

**Comment by brechtm** [comment]
Agreed. This will be changed in 0.3.1.

**Comment by sachin-suresh-rapyuta** [comment]
Can I know an example on how to override the title page logo in the .rts file?

**Comment by brechtm** [comment]
@sachin-suresh-rapyuta I hope my answer to [your question on StackOverflow](https://stackoverflow.com/questions/72695374/rinohtype-sphinx-customize-the-styles-in-pdf) addresses this?
