### ISSUE TITLE
Date is not displayed in the fron page

### ISSUE THREAD

**Issue by pcav** [brechtm/rinohtype#61]
Apparently this is due to previous ticket (large logo)

**Comment by brechtm** [comment]
This can happen when you include a large logo on the title page (as in the Lizmap documentation for example). The space between the title page elements is fixed at the moment. You can override them by specifying a custom style sheet in conf.py:

```
	from rinoh.style import StyleSheetFile

	rinoh_stylesheet = StyleSheetFile('lizmap.rts')
```

And lizmap.rts::

```
    [STYLESHEET]
    name=LizMap custom style
    description=Small tweaks made to the Sphinx style sheet
    base=sphinx

    [title page author]
    typeface=$(sans_typeface)
    font_weight=bold
    font_size=17pt
    text_align=right
    space_above=20pt

    [title page date]
    typeface=$(serif_typeface)
    font_size=12pt
    text_align=right
    space_above=20pt
```

These are copies of the styles defined in sphinx.rts (included with rinohtype), replacing space_above with smaller values. In a future release, it will be possible to inherit from a style, so you don't have to copy the unchanged values.

It would of course be nice if this could be handled automatically, depending on the size of the logo, but this is not a high priority feature IMO.

**Comment by brechtm** [comment]
In rinohtype 0.3.0, styles in the style sheet extend (instead of replace) the style of the base style sheet. So you now only have to specify the options you want to change:

```ini
[STYLESHEET]
name=LizMap custom style
description=Small tweaks made to the Sphinx style sheet
base=sphinx

[title page author]
space_above=30pt

[title page date]
space_above=30pt

[table of contents]
depth=3
```

Please consult the [documentation](http://www.mos6581.org/rinohtype) to see which styles and options can be customized.
