### ISSUE TITLE
Table of content and Index entries are not colored

### ISSUE THREAD

**Issue by pcav** [brechtm/rinohtype#62]
whereas in Latex equivalent they are

**Comment by brechtm** [comment]
They are clickable in all PDF viewers I have installed (Apple Preview, Skim, Adobe Reader, PDF-XChange, Foxit, SumatraPDF, Evince). Which PDF viewer are you using?

The clickable text is not displayed in a different color as is the case in the LaTeX output. Perhaps this is what you are referring to?

**Comment by pcav** [comment]
Oh, you're right, sorry for the noise. For consistency, and the Principle of Least Surprise, however, I'd suggest to change the colour here as well.
Thanks.
