### ISSUE TITLE
Rinohtype for education?

### ISSUE THREAD

**Issue by chbuschmann** [brechtm/rinohtype#90]
In one form or another this might have been answered. My opinion is that LaTeX is great in education; with templates it is easy to unleash ease of writing and creativity, but what about Rinohtype? Examples/cases for both teacher/student is much obliged.

**Comment by brechtm** [comment]
Sure, rinohtype can definitely be used in education. I'm not sure I understand the question though. Please elaborate.

As for templates; the idea is to include a limited set of templates and style sheets with rinohtype. Others can be published on [PyPI](https://pypi.python.org/pypi). For those not familiar with Python, I would like to eventually offer an easy way to browse and install these.
