### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by pepa65** [brechtm/rinohtype#96]
`sudo pip install rinohtype` on Ubuntu 16.04 fails with:
```
Complete output from command python setup.py egg_info:
rinohtype requires Python 3.3 or higher
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k0AqTj/rinohtype/
```
python 3.5 is installed.

**Comment by sputtene** [comment]
I had the same problem. Use `sudo pip3 install rinohtype` instead.

You might need to `sudo apt install python3-pip` first.

**Comment by pepa65** [comment]
Thank you for responding. It's installing now!
Would be great if this got added to the instructions.

**Comment by brechtm** [comment]
Thanks for chipping in @sputtene! I'm slowly getting back to rinohtype after my vacation and FOSDEM.

I added a FAQ entry in b3d533136aa767d3fa4754c9b5a51a86c6633345.

**Comment by sputtene** [comment]
You're welcome :)

I'm slowly getting up to speed with rinohtype after your FOSDEM talk.

I'm going to implement a Textile parser (the markup language used by e.g. Redmine) and see how I can create a style sheet to have rinohtype generate PDFs that comply to the style guide of the company I work for.

Thanks for answering my question about a Textile frontend during your FOSDEM talk by the way!
