### ISSUE TITLE
suggested demo.txt maybe not the best for running rinohtype for the very first time

### ISSUE THREAD

**Issue by PedroLopes** [brechtm/rinohtype#97]
(minor issue here, using last rinohtype from git/master)

While installing and testing the demo example suggested in the README:
``rinoh demo.txt``
fails with ``Cannot determine input format from extension 'txt'. Specify the format using the `--format` option. Run `rinoh --list-formats` to find out which formats are supported.``

...which makes sense because the format should be ``.rst`` (e.g., ``mv demo.txt demo.rst``). 

p.s.: great talk at fosdem, thanks for introducing me to this amazing project. I will be using it for sure!

**Comment by brechtm** [comment]
Thanks. Good point. I'm thinking of replacing `demo.txt` with the `README.rst` itself, but it contains URLs to images, so the output won't be pretty. I'm not sure if I should support loading images from URLs.
